multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/share/pkg.7/python3/3.7.7/install/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/share/pkg.7/python3/3.7.7/install/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr3/graduate/salomonw/Github/mixed-traffic-amod-route-rebalance/experiments/run_penRate_intermodal_journal.py", line 59, in solve_stackelberg_game
    tNet_non_cavas.build_layer(one_way=True, avg_speed=0.0001, capacity=99999, symb="b", identical_G=False)
NameError: name 'tNet_non_cavas' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/share/pkg.7/python3/3.7.7/install/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/share/pkg.7/python3/3.7.7/install/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr3/graduate/salomonw/Github/mixed-traffic-amod-route-rebalance/experiments/run_penRate_intermodal_journal.py", line 290, in <module>
    result = penRate(netname,dir_out=dir_out,rebalancing=rebalancing, n=n, theta_n=theta_n, linear=linear,  demand_multiplier=demand_multiplier, n_iter=n_iter, parallel=parallel)
  File "/usr3/graduate/salomonw/Github/mixed-traffic-amod-route-rebalance/experiments/run_penRate_intermodal_journal.py", line 172, in penRate
    results = pool.map(solve_stackelberg_game, pars)
  File "/share/pkg.7/python3/3.7.7/install/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/share/pkg.7/python3/3.7.7/install/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
NameError: name 'tNet_non_cavas' is not defined
